[tools]
bat = "latest"
btop = "latest"
bun = "latest"
delta = "latest"
duckdb = "latest"
eza = "latest"
fd = "latest"
go = "latest"
just = "latest"
lazygit = "latest"
neovim = "latest"
postgres = "latest"
prek = "latest"
rg = "latest"
rust = "latest"
uv = "latest"
zig = "latest"
zoxide = "latest"
