[tools]
bat = "latest"
btop = "latest"
bun = "latest"
claude = "latest"
codex = "latest"
delta = "latest"
duckdb = "latest"
eza = "latest"
fd = "latest"
go = "latest"
java = "temurin"
just = "latest"
lazygit = "latest"
"llama.cpp" = { version = "latest", version_prefix = "b" }
neovim = "latest"
oci = "latest"
pi = "latest"
postgres = "latest"
prek = "latest"
rg = "latest"
rust = "latest"
uv = "latest"
zig = "latest"
zoxide = "latest"
