[tools]
bat = "latest"
btop = "latest"
delta = "latest"
duckdb = "latest"
eza = "latest"
fd = "latest"
go = "latest"
lazygit = "latest"
neovim = "nightly"
postgres = "latest"
rg = "latest"
rust = "latest"
uv = "latest"
zoxide = "latest"
